supabase/postgrest-js

src/Builder.js
src/Request.js
src/utils/Filters.js
test/integration/PostgrestClient.test.js
test/unit/Rest.test.js

Simply put:
- The previous functionality of .not() is now .neq()
- .not() now serves a bigger function in now acting as the complete opposite to the .filter() function. .not() squeezes in the string `.not` into the final query.
- Based on [this](http://postgrest.org/en/v6.0/api.html#operators).

New Concept for .not()

---

src/Builder.js
src/Request.js
src/utils/Filters.js
test/integration/Filters.test.js

Adds support for OR filter like so:
```js
client.from('countries').or('id.gt.20,and(name.eq.New Zealand,name.eq.France)')
```
Support for AND is not added because they're redundant with chaining filters.
Closes #44.

feat: support OR filter

---

src/builder.ts

Bug fix.
postgrest-js@0.18.0 doesn't work in the browser.
I'm using WHATWG `URL` to build the URL + query parameters. But I used it from Node's built-in `url` module, which clearly [doesn't exist in the browser](https://codesandbox.io/s/vigilant-moon-1o4g9). Rookie mistake!
`URL` is also [available globally](https://nodejs.org/api/url.html#url_class_url) in Node, so I'm removing the import to make this work in the browser.

fix: proper usage of isomorphic URL

---

package-lock.json
package.json
src/builder.ts

Bug fix.
There's [some problems](https://codesandbox.io/s/compassionate-mayer-5nk8h) using postgrest-js from jspm, probably related to https://github.com/developit/unfetch/issues/104 and https://github.com/developit/unfetch/pull/109. The repo doesn't look too healthy, so I'm switching to [cross-fetch](https://github.com/lquixada/cross-fetch) for the fetch polyfill, which uses [github/fetch](https://github.com/github/fetch) under the hood.

fix: change fetch polyfill

---

src/builder.ts

When building several queries using a single PostgrestClient instance, calling `single` will break subsequent requests since the headers object it mutates is currently shared across all queries. This PR changes the behaviour so the query builder always receives a fresh headers object that is safe to mutate.
First request
```ts
this.data.from("properties")
.select("*")
.filter("id", "eq", id))
.single()
```
Expect: JSON Object
Receive: JSON Object
Second request
```ts
this.data.from("properties")
.select("*")
```
Expect: Result Set
Receive: Error: Results contain 3 rows, application/vnd.pgrst.object+json requires 1 row
No errors are observed when the two queries above are run. Each query receives its own copy of the headers object.
Affected versions: 0.18.x, 0.19.0

don't mutate headers

---

src/builder.ts
test/__snapshots__/transforms.test.ts.snap
test/transforms.test.ts

Feature.
Allow vertical filters and transforms on the result of `insert()`. E.g.:
```js
const { error, data } = await postgrest
.from('users')
.insert({ ... })
.single()
```
Most of the time, we just want a single object for the above.

Allow filters and transforms on insert

---

src/PostgrestClient.ts
src/lib/PostgrestTransformBuilder.ts
src/lib/types.ts
test/basic.test.ts

r? @soedirgo @kiwicopple (I might need some help with updating the test snapshots)
- Make `PostgrestResponse` data always an array
- Introduce `PostgrestSingleResponse` and make `single` return `PromiseLike<PostgrestSingleResponse<T>>`
- This means `single` has to be called at the very end of the method chain in a TypeScript context. 
- Make sure `PostgrestResponse` is correctly assigned as the return type of `onfulfilled` callback.
I've tested this in a TypeScript project:

chore: Types improvements.

---

src/lib/PostgrestTransformBuilder.ts
test/__snapshots__/basic.test.ts.snap
test/basic.test.ts

Bug fix.
Previously, `order` columns wrap the column name in quotes to allow
characters like `.` without having the user wrap it manually, but this
breaks on JSON columns, so we're removing the quotes.
Closes #131.

Fix ordering on JSON columns

---

src/lib/types.ts

A typing enhancement. The response types are not as accurate as they could be
A response from postgrest currently looks like
```ts
interface PostgrestResponse<T> {
error: Error | null
data: T | null
}
```
this means that typescript cannot infer whether we are dealing with an errored response or a successful response. For example:
```ts
const res = supabase.from('my_table').select()
if (res.error) throw new Error('something went wrong')
for (const row of res.data) { // <- typescript will give a compiler error here that `res.data` is possibly undefined
// do something...
}
```
in this case, we _know_ that data is populated, because error is null (shown here https://github.com/supabase/postgrest-js/blob/master/src/lib/types.ts#L75-L81). The workaround is to throw a non-null assertion …

Postgrest response types are a union of 'error' and 'data'

---

src/PostgrestClient.ts
src/lib/PostgrestQueryBuilder.ts
src/lib/PostgrestTransformBuilder.ts
test/__snapshots__/index.test.ts.snap
test/db/00-schema.sql
test/transforms.ts

Feature.
Can't do vertical filtering on INSERT/UPDATE/DELETE.
Allow vertical filtering (`select`) during transform (i.e. at the end of the method chain):
```js
await postgrest
.from('items')
.update({ quantity: 1 })
.eq('category', 'fruits')
.select('id,xmax')
await postgrest
.rpc('get_username_and_status', { name_param: 'supabot' })
.select('status')
```
Closes #143.

feat: add vertical filtering on CUD

---

src/PostgrestClient.ts
src/lib/PostgrestQueryBuilder.ts
src/lib/PostgrestTransformBuilder.ts
src/lib/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts
test/transforms.ts

It will add `head` and `count` option to allow querying row count. 
Cannot get row count. 
Enable retrieving row count. 
#94

Adding head and count option on select(), insert(), update(), delete(), and rpc()

---

src/lib/PostgrestQueryBuilder.ts

Tiny optimization to not set the headers twice (one call less).
If count is set, headers will be joined and set again
Headers will only be set once

Remove duplicate assignment of headers

---

src/lib/PostgrestFilterBuilder.ts
src/lib/PostgrestTransformBuilder.ts

Automatically quoting tables/columns led to many unintended problems: #131, #149. This removes all remaining quoting of names.
Bug fix.
Closes #149.

fix: remove quoting of names

---

src/PostgrestClient.ts
src/lib/PostgrestQueryBuilder.ts
src/lib/PostgrestRpcBuilder.ts
src/lib/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts
test/db/00-schema.sql

- Create PostgrestRpcBuilder
- Move `rpc` method from PostgrestQueryBuilder to PostgrestRpcBuilder
- Fixes `PostgrestClient.rpc()` options param 
- Improve fetch response + error parsing (fixes https://github.com/supabase/supabase-js/issues/132)
- Fixes stored procedure unit tests
- When `rpc` method insides PostgrestQueryBuilder. User can create this chain
`let res = await postgrest.from('users').rpc({ name_param: 'supabot'})` 
It's wrong.
- no way to set options param
- No breaking change. `postgrest.rpc` usage is the same after moving it to PostgrestRpcBuilder
- Expose `rpc` options param

fix: rpc method

---

src/lib/PostgrestFilterBuilder.ts
test/__snapshots__/index.test.ts.snap
test/resource-embedding.ts

Postgrest supports embedded filters through the following syntax https://postgrest.org/en/v7.0.0/api.html#embedded-filters
Filtering a sub selection in postgres with `or`/`and` for the foreignTable.
Required workaround query param format based on an extended version of the supabase todos example:
```js
const start = new Date().toISOString();
const end = new Date().toISOString();
const workaroundParam = `todos.or=(completed_at.is.null,and(completed_at.gte.${start},completed_at.lt.${end}))`
await client
.from(`projects?${workaroundParam}`)
.select('id,todos(id,completed_at)')
.eq('id', 1)
.order('inserted_at', { foreignTable: "todos", ascending: false });
```
Update the or filter to support foreignTable handling to achieve the desired output of postgrest which doesn't require hacking it …

support embedded or filter

---

src/lib/PostgrestTransformBuilder.ts
test/__snapshots__/index.test.ts.snap
test/resource-embedding.ts
test/transforms.ts

Adds support to order by more than a single column in both embedded table and top level columns as per postgrest https://postgrest.org/en/v7.0.0/api.html?highlight=order#ordering.
Overwrites the single order param only allowing the latest in the call chain to resolve.
Appends order clauses comma delimited for the query instance.

support multliple column order

---

src/lib/PostgrestFilterBuilder.ts

fixes https://github.com/supabase/postgrest-js/issues/164
This only quotes values and not column names. Previous bugs were due to quoting column names. 
I also add in a check to only quote the value if the filter value contains a postgrest special character.

fix: handle postgrest special characters in filters

---

src/lib/PostgrestQueryBuilder.ts
test/basic.ts
test/resource-embedding.ts

Feature.
UPSERT is done through `insert()`, which might confuse some users.
Make UPSERT its own function.
Closes #161.

Make UPSERT its own function

---

src/lib/PostgrestQueryBuilder.ts
test/basic.ts

Bug fix.
Bulk insert doesn't have [columns](https://postgrest.org/en/stable/api.html#specifying-columns) param.
Adds the param. Fixes #175.

fix: include `columns` param on bulk INSERT

---

src/PostgrestClient.ts
src/lib/PostgrestRpcBuilder.ts
test/filters.ts

Bug fix.
Stored procedures (`rpc()`) return `PostgrestTransformBuilder` and thus doesn't support filters (`eq()`, etc.).
Return `PostgrestFilterBuilder` to support filters.

fix(rpc): allow filters on rpc

---

src/lib/PostgrestQueryBuilder.ts
test/basic.ts

Bug fix.
`insert()` with empty body, i.e. no columns in any of the values (e.g. `[{}, {}]`) gives a `columns` query parameter with no value, leading to `failed to parse columns parameter ()` error.
Omit `columns` param when no column is specified.

fix: insert w/ empty body can't have columns param

---

src/lib/PostgrestTransformBuilder.ts
src/lib/types.ts

Feature
Response is always a JSON.
Ability to set response type to CSV. Usage:
```
postgrest
.from('table')
.csv()
.select()
```
CSV responses can be super convenient for some use cases (https://github.com/supabase/postgrest-js/issues/186) but also save plenty of resources used (wasted) by large response sizes (https://github.com/supabase/supabase-js/issues/189)

CSV Response

---

src/lib/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts

This adds an `unwrap()` function on the PostgrestBuilder class, which means errors will be thrown instead of returned.
Basic tests were added to test/basic.ts and the unwrap function is documented to some degree at least, though this can probably be improved. This should be a non-breaking change as it just adds functionality, it doesn't change any existing features.
Supabase queries return errors as part of a successful response, i.e. the promise is resolved. The exception (no pun intended) to this is if there's something wrong with the fetch call itself, such as a network error – these will lead to the promise rejecting and can be handled in a try/catch block. This leads to somewhat awkward code:
```javascript
try {
const { data, error } = await supabase.from('my_table').select()
if …
```

Implement unwrap() to throw query errors instead of returning them

---

src/index.ts
src/lib/types.ts

Feature.
Exports `PostgrestResponse`, `PostgrestSingleResponse`, `PostgrestMaybeSingleResponse`, `PostgrestError`.
Required for https://github.com/supabase/supabase-js/issues/168.

feat: export error and response types

---

src/lib/PostgrestQueryBuilder.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts

As requested (https://github.com/supabase/supabase/discussions/1834 & https://github.com/supabase/postgrest-js/issues/189) this PR implements the `Prefer: resolution=ignore-duplicates` header to ignore duplicates in an upsert operation.
More information on the `Prefer: resolution=ignore-duplicates` header can be found here: https://postgrest.org/en/stable/api.html#upsert
Currently not implemented so the only option for an upsert is for it to be merged.
Now users have the option to ignore duplicates instead of merging them.

feat: add ignoreDuplicates option to upsert

---

src/lib/PostgrestQueryBuilder.ts
test/basic.ts

Bug fix.
Can't use `(`, `)`, and other symbols in bulk insert.
Escape `columns` query param so it can be done.

fix: escape `columns` query param

---

src/lib/PostgrestTransformBuilder.ts

Not all errors returned by postgrest contain the `details` field (in particular, 401 errors due to invalid/expired JWT tokens). Hence, this PR avoids an uncaught promise rejection by ensuring that `error.details` field exists before checking the error details for the "Results contain 0 rows" message.
If the result from postgrest has an error status code, and the error response does not have the `details` field, an uncaught rejection will be thrown when used with the `maybeSingle()` modifier.
The commit avoids throwing such errors by ensuring the `details` field exists.
Nil
**Note:** I didn't run the existing tests as I didn't have Docker setup on my device. Do let me know if I should add additional tests for this as well.

maybeSingle: Avoid uncaught promise rejection

---

src/PostgrestClient.ts
src/lib/PostgrestRpcBuilder.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts
tsconfig.json

Feature.
RPC function calls are made only using `POST`.
Users can customize the HTTP request type to ~~`GET` or~~ `HEAD`. This allows for selecting the count of rows in a function call returning a table without selecting any data with the `HEAD` request type and `count` option.
- I made use of `Object.entries`, but if there's any browser compatibility requirements I can just revert to a `for`-`in` loop.
- This also required editing the `tsconfig.json` to recognize newer ES methods
- I also didn't account for the edge case where an array parameter is passed with a `GET`/`HEAD` request. Seems like there are two possible usages of this: https://postgrest.org/en/v8.0/api.html#calling-functions-with-array-parameters and https://postgrest.org/en/v8.0/api.html#calling-variadic-functions and I'm …

Allow customizing RPC request method

---

README.md
src/PostgrestClient.ts
src/lib/PostgrestQueryBuilder.ts
src/lib/PostgrestRpcBuilder.ts
src/lib/types.ts

This PR adds the ability to provide a custom `fetch` implementation as an option - this is most useful for environments where `cross-fetch` is not supported, for instance Cloudflare Workers or Vercel Edge Functions.
This is related to https://github.com/supabase/supabase-js/issues/154, and I believe a similar option would need to be added to the other libraries using `cross-fetch` before being finally added to `supabase-js`.
At the moment, `cross-fetch` is always used in all environments.
There is a new option `fetch` that can be provided to override `cross-fetch` with an alternative library (or the native `fetch`):
```js
import { PostgrestClient } from '@supabase/postgrest-js'
const REST_URL = 'http://localhost:3000'
const postgrest = new PostgrestClient(REST_URL, { fetch: fetch })
``` …

feat: allow providing custom fetch implementation

---

README.md

This updates the documentation example of providing a custom `fetch` implementation (introduced in https://github.com/supabase/postgrest-js/pull/222). While the previous example was conceptually correct, in most environments it's not possible to assign a native built-in function like `fetch` to an object, as calling it later will attempt to call the native function in the context of the object and throw an `illegal invocation` error.
Creating a new fetch function by binding to the global scope, for instance `fetch.bind(global)` in Node or `fetch.bind(self)` in Cloudflare Workers, fixes this issue, but creating a new arrow function is the most univerally functional example since it doesn't require you to know if `global` is defined or not, so this PR uses that as an example:
```js
{
fetch: …
```

fix(docs): update custom fetch example

---

src/lib/types.ts

Bug fix.
The fetch method tries to parse error response as JSON before returning. Whenever the error response is not a JSON object, it will not return properly instead a JSON parsing error will be thrown.
The fetch method tries to parse error response as JSON before returning, in case of failure returns a raw text error.
Fix #241

fix: Fetch method can't handle error response that is not a valid JSON

---

src/lib/PostgrestQueryBuilder.ts
test/basic.ts

Adds the ability to add custom `prefer` headers such as [Prefer: tx=rollback](https://postgrest.org/en/stable/configuration.html#db-tx-end). 
Custom prefer headers will take precedence over the existing `prefer` heaaders.
Bug fix, feature, docs update, ...
#243 
Current [implementation](https://github.com/supabase/postgrest-js/blob/eab227d2fb0eacd5fc4b1bc355183050a5ca40d9/src/lib/PostgrestQueryBuilder.ts#L112) overwrites custom `Prefer` headers that are passed during client initialisation
Custom Prefer Headers gets prepended to the existing prefer headers.

feat: support for custom prefer headers #243

---

src/lib/types.ts

Because JS is such a beautiful language.
`globalThis` is neater but might hurt compatibility (2019+)

fix: illegal invocation on fetch

---

src/PostgrestClient.ts
src/lib/PostgrestQueryBuilder.ts
src/lib/PostgrestRpcBuilder.ts
src/lib/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts

Currently, throwOnError can be set to true for any given query (/rpc
call). This change allows the flag to be set to true at client
initialization time, ensuring that you do not need to rely on each
invocation either handling the error returned, or setting the flag
correctly.

feat: support setting throwOnError at the client level

---

src/lib/types.ts
test/basic.ts

Bug fix for typings
You cannot chain modifiers after `PostgrestBuilder.throwOnError()` because the return type is the base abstract class.
The return type should be `this` so that you can continue to add modifiers.
Test change indicates the chaining order that is now supported.

fix(types): update throwOnError return type to "this"

---

.gitignore
src/lib/PostgrestTransformBuilder.ts
src/lib/types.ts
test/basic.ts

Bug Fix
closes #271 
Currently, `throwOnError()` throws if empty results are received despite `maybeSingle()`. See #271 for details.
```ts
const { data, error } = await supabaseClient
.from('channel')
.update({ active: false })
.eq('id', channelId)
.throwOnError(true)
.maybeSingle(); 
console.error(error) // null, and no error is thrown
```

fix: make throwOnError work with maybeSingle

---

src/PostgrestQueryBuilder.ts
src/PostgrestTransformBuilder.ts
test/basic.ts
test/transforms.ts

Please review https://github.com/supabase/postgrest-js/pull/275 first 🙏
BREAKING CHANGE: set `Prefer: return=minimal` by default everywhere
We previously set `returning = 'representation'` by default so that
inserted/updated/deleted rows are returned. We now change the default so that
inserted/updated/deleted rows are NOT returned.
To return inserted/updated/deleted rows, call `.select()` at the end of
the call chain.

feat: set `Prefer: return=minimal` by default

---

src/PostgrestTransformBuilder.ts

BREAKING CHANGE: nullsFirst = true by default
We previously set `nullsFirst = false` by default, but it caused some perf issues: https://github.com/supabase/postgrest-js/issues/239

perf: nullsFirst = true by default

---

src/PostgrestBuilder.ts
src/PostgrestClient.ts
src/PostgrestFilterBuilder.ts
src/PostgrestQueryBuilder.ts
src/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts
test/filters.ts
test/transforms.ts

BREAKING CHANGE: use undefined as bottom value instead of null

feat: use undefined as bottom value instead of null

---

src/PostgrestBuilder.ts
src/PostgrestClient.ts
src/PostgrestFilterBuilder.ts
src/PostgrestQueryBuilder.ts
src/PostgrestTransformBuilder.ts
src/select-query-parser.ts
src/types.ts
test/basic.ts
test/filters.ts
test/resource-embedding.ts
test/transforms.ts
test/types.ts

BREAKING CHANGE: Rework typings.
Closes https://github.com/supabase/postgrest-js/issues/172, closes https://github.com/supabase/postgrest-js/issues/217.
The current typings DX is not great. The way users supply types is through `.from<T>()` which needs to be done on each call. What ends up happening most of the time is users would leave the `T` which defaults to `any`, because this is the path of least resistance.
Another sticking point is the `T` above also becomes the query result type, even though you can e.g. specify only certain columns.
This change intends to alleviate the above by 1) accepting type definitions at the constructor, and 2) parsing `.select()` query to infer the result type.
As an example, using the type definitions in `test/types.ts`: …

Improved typings

---

src/lib/PostgrestTransformBuilder.ts
test/__snapshots__/index.test.ts.snap
test/db/00-schema.sql
test/db/01-dummy-data.sql
test/db/docker-compose.yml
test/transforms.ts

Adds support for:
- explain: https://github.com/PostgREST/postgrest/pull/2368
- geojson: https://github.com/PostgREST/postgrest/pull/1564

Adds `explain()` and `geojson()` transforms

---

src/PostgrestClient.ts
src/PostgrestQueryBuilder.ts
test/basic.ts
test/db/00-schema.sql
test/db/docker-compose.yml
test/types.ts

Rollback was added back in https://github.com/supabase/postgrest-js/pull/244 but it's a global parameter. This PR adds a rollback that can be enabled per request - for mutations and rpc(`select` is possible but not useful, so it's not included).
rollback is needed for EXPLAIN ANALYZE(since it executes the query):
```js
const res = await postgrest
.from('users')
.delete({rollback: true})
.explain({analyze: true})
```

feat: add rollback parameter to mutations and rpc

---

src/PostgrestBuilder.ts
src/PostgrestTransformBuilder.ts
test/transforms.ts

json format for explain was added in https://github.com/supabase/postgrest-js/pull/293 but it's hard to read. This PR adds a text format so it looks like:
```js
postgrest.from('users').select().explain({format: 'text'}).then(({ data, error }) => console.log(data, error))
Aggregate  (cost=17.65..17.68 rows=1 width=112)
->  Seq Scan on users  (cost=0.00..15.10 rows=510 width=132)
```

feat: add text format to explain()

---

src/PostgrestTransformBuilder.ts
test/transforms.ts

EXPLAIN in text format is more readable as mentioned in https://github.com/supabase/postgrest-js/pull/301

change explain() default format from json to text

---

src/PostgrestBuilder.ts
src/types.ts
test/__snapshots__/index.test.ts.snap
test/basic.ts
test/filters.ts
test/transforms.ts

To make it consistent with other client libs. Will decide on `null` vs. `undefined` in response for supabase-js v3.

feat: revert to `null` in response

---

package-lock.json
package.json
src/PostgrestBuilder.ts
src/PostgrestClient.ts
src/PostgrestFilterBuilder.ts
src/PostgrestQueryBuilder.ts
src/PostgrestTransformBuilder.ts
src/select-query-parser.ts
test/basic.ts
test/index.test-d.ts
tsconfig.json

feature
Result type for `.select()` cannot be overridden. Since typings for nested relations is still a WIP, we need an escape hatch so people can set the types for specific fields.
Support overriding the types for specific fields. E.g. from the tests:
```ts
// can override result type
{
const { data, error } = await postgrest
.from('users')
.select('*, messages(*)')
.returns<{ messages: { foo: 'bar' }[] }>()
if (error) {
throw new Error(error.message)
}
expectType<{ foo: 'bar' }[]>(data[0].messages)
}
```
Additionally, instead of always returning `unknown` for all nested relations, we instead return `T | T[]`. This is as specific as we can get despite the [ambiguity](https://github.com/supabase/postgrest-js/issues/303#issuecomment-1220525868).

feat: allow overriding result types

---

src/PostgrestClient.ts
src/PostgrestFilterBuilder.ts
src/PostgrestQueryBuilder.ts
src/PostgrestTransformBuilder.ts

This makes the doc comments show up for all the function signatures, instead of just the first one.
Before:
https://user-images.githubusercontent.com/31685197/203481350-f04dea46-efdd-4492-b915-f324c1971c6b.mov
After:
https://user-images.githubusercontent.com/31685197/203481364-b1646a4a-9a05-4d17-bfa0-7246fb52a061.mov

docs: move doc comments to func impl

---

src/select-query-parser.ts
test/index.test-d.ts

Postgres supports [accessing properties in JSON and JSONB columns](https://www.postgresql.org/docs/current/functions-json.html) by using the `->` and `->>` operators. Postgrest [supports this too](https://postgrest.org/en/stable/api.html#json-columns). However, trying to use this in the Supabase `select` API makes Typescript barf:
```typescript
/* schema: users: { Row: { data: Json } } } */
const { data } = await db.from('users').select('data->username, data->>numLikes')
// inferred type of `data` is `ParserError<'Unexpected input: ->username, data->>numLikes'>[] | null`
```
This small extension to the query parser types makes simple `column->foo->bar->>baz` property chains work properly, e.g. the above query will infer a type of `{ username: Json, numLikes: string }`. 
Note that this …

Extend query parser w/basic support for `->`/`->>` JSON operators

---

tsconfig.json

I noticed that my Typescript was complaining because code in `PostgrestFilterBuilder` uses `Object.entries`, which is an ES2017 method, but Typescript was only targeting ES2015.
AFAIK ES2017 is supported by all modern browsers, so I suggest just bumping the target. You can see here for some compatibility tables: https://kangax.github.io/compat-table/es2016plus/
If you really like targeting ES2015 for a reason I don't know, you could leave the target alone and use the `lib` property to express that you expect ES2017 library functions to exist: https://www.typescriptlang.org/tsconfig#lib

Target ES2017 in tsconfig

---

src/PostgrestQueryBuilder.ts

Bug fix
If `return=minimal` (i.e. insert/update/upsert/delete w/o returning modified rows) `data` is typed as `undefined` instead of `null`.
`data` is typed as `null` on `return=minimal`.

fix: use `null` if `return=minimal`

---

src/index.ts
src/types.ts

Type change. Discussion here: https://github.com/supabase/supabase/discussions/12228
Only the top-level `PostgrestResponse` types are exported.
Export the sub-types that go into `PostgrestResponse` for type-union/guard-clause purposes.
I noticed the plan is to rename `PostgrestSingleResponse` and deprecate the current `PostgrestResponse`, so instead of exporting `PostgrestSingleResponseSuccess` under its current name I went with `PostgrestResponseSuccess`.
This _might_ mean holding the change back until v3, but since its to a (formely) internal type we should be okay.

Export PostgrestResponseSuccess and PostgrestResponseFailure

---

src/PostgrestQueryBuilder.ts

I could not find a note about it in the docs so far

Explain renaming of returned columns

---

src/select-query-parser.ts
src/types.ts
test/index.test-d.ts

Resolves #398
DX improvement
`.select` with multiple columns returns an intersected type:
Intersected type is prettified:

Prettify intersected types when selecting multiple columns

---

src/select-query-parser.ts

Feature: Support double-quoted identifiers in select-string
Error reported about quoted identifier. Type-hinting fails.
Type-hinting succeeds:

Support for double-quoted identifiers in queries

---

src/PostgrestFilterBuilder.ts
src/PostgrestQueryBuilder.ts
src/PostgrestTransformBuilder.ts
src/select-query-parser.ts
test/index.test-d.ts
test/types.ts

Fixes #303 
Nested tables are typed as `T[] | T | null` - it's annoying to always have to use type guards for these.
Infer relationship cardinality (i.e. *-to-one or *-to-many) so nested tables are typed as either `T[]` or `T | null`

feat: determine relationship cardinality from types

---

src/select-query-parser.ts
test/index.test-d.ts

The type for columns that do not exist in the schema, which used to be `? ` to `null`.
Currently, given a column that does not exist, the property can still be specified.
If a non-existent column is given, the user cannot specify a non-existent column in order to return null.
This makes it easier to recognize column name problems from why they are null or from errors.
It may be that this should return an error type similar to `ParserError` , `GenericStringError`, etc., but I think that would greatly expand the area to be modified.

Type change for columns that do not exist in the schema

---

src/PostgrestTransformBuilder.ts

Docs update
These updates are based on feedback in the Supabase repo's issue #15222 (https://github.com/supabase/supabase/issues/15222)
The original docs state that "range" takes a starting index and ending index and returns the values between them. This implies that it's using the primary ID. But it actually works more like limit + offset.
I've updated the docs to explain how it works in greater detail.

Documentation improvements for the `range()` method

---

src/PostgrestFilterBuilder.ts
test/filters.ts

Mark arrays accepted by filter builder methods readonly.
Currently filter builder methods accept non-readonly arrays. This is fine, but forces casting readonly arrays to non-readonly versions even though Supabase methods do not mutate the passed-in arrays.
See:
```ts
const ALLOWED_STATUSES = ["ACCEPTED", "PENDING"] as const;
supabase.from("tasks")
.select()
.eq("status", ALLOWED_STATUSES) // tsc error: Argument of type 'readonly (..)[]' is not assignable to parameter of type '(..)[]'.
```
All filter builders accepting arrays will accept the readonly version. Since this only changes function parameter signature and none of the returned values, it should be a non-breaking change.
Quite many libraries (and notably, Typescript's own `as const`) use readonly arrays, so this makes working with …

Mark array filter values readonly

---

src/PostgrestQueryBuilder.ts

docs update
`defaultToNull` only applies when doing bulk inserts/upserts, but this isn't reflected in the docs
Update the docs
https://github.com/supabase/postgrest-js/pull/417#discussion_r1269573654

chore(docs): add note re: defaultToNull

---

src/PostgrestClient.ts
test/basic.ts

Resolves https://github.com/supabase/postgrest-js/issues/280
New feature
See discussion on https://github.com/supabase/postgrest-js/issues/280
The current behavior is that the `PostgrestClient` is created with a schema passed into the constructor. The class instance cannot reference tables or rpc calls for any other schemas unless a new instance is created.
```ts
// implicitly "public" schema
const postgrestPublic = new PostgrestClient<Database>(REST_URL)
// explicit specification of non-public schema
const postgrestPersonal = new PostgrestClient<Database, 'personal'>(REST_URL, { schema: 'personal' })
postgrestPublic.from('users').select() // select users from the "public" schema
postgresPersonal.from('users').select() // select users from the "personal" schema
```
A single class instance …

feat: add dynamic schema to postgrest client

---

src/PostgrestFilterBuilder.ts
test/index.test-d.ts

Currently, `.eq()` allows null inputs but crucially it won't work, as you need to use `.is()` for null comparisons.
This PR adds stronger typing to ensure that null values are not passed to `.eq()`. Instead, you'll either have to do non-null assertion or a more proper method, like `.is()` or `.eqNullable()` (#463)
Note: this is kind of a breaking change, but I think an extremely useful one and call sites where this causes errors should be fixed

Enforce non-null parameter to .eq

---

test/index.test-d.ts

Release https://github.com/supabase/postgrest-js/pull/464 - commit didn't have `fix:`

fix: trigger release

---

src/PostgrestBuilder.ts

Fixes #361.
On PostgREST 11.2.0, the format of the error got changed on PostgREST/postgrest#2876 to "The result contains 0 rows".
Change the detection to "0 rows". This should be backwards compatible.

fix: detection of maybeSingle

---

src/PostgrestTransformBuilder.ts
test/db/docker-compose.yml
test/transforms.ts

Bug fix. Closes #504
Sends `"undefined"` media type when requesting explain plan, making the explain() method fail.
Sends `"application/json"` as media type.
Tests weren't failing because they were using PostgREST v11.0.0 instead of v11.2.2

fix: explain() always returning an error

---

src/PostgrestTransformBuilder.ts

Thought it would be helpful to include a link on how to enable the `explain()` feature on the method itself so that people know how to enable it.

fix: add link on how to enable explain on the explain() method

---

src/PostgrestFilterBuilder.ts

Dedup values passed into  PostgrestFilterBuilder.in
Values are incorporated into the url as is when duplicate values are present.  
e.g. .in([1,1,2,2,3,3]) => `in.(1,1,2,2,3,3)`
The caused us to get a 414 URI too long when we passed in a long array of deduplicated values by accident.  Would be nice if the library took care of this.
Values will be deduplicated as duplicated.  
e.g. .in([1,1,2,2,3,3]) => `in.(1,2,3)`

dedup values passed to PostgrestFilterBuilder.in

---

src/select-query-parser.ts

This change adds support for type casting in select queries. For example an id column with the type bigint can be casted to text by "id::text".
Equivalent PostgreSQL type for TypeScript type is based on the type generator [pgTypeToTsType](https://github.com/supabase/postgres-meta//blob/80809c71d78d875524d7d9865c2458136207aa10/src/server/templates/typescript.ts#L421) function.
Fixes https://github.com/supabase/postgrest-js/issues/370
- `id::text` will cast a `bigint` column to `string` in TypeScript.
- `_text` will be `text[]`.
- `newname:id::text` will also work
This is by no means a complete list of all possible type casts nor is it sound, but this is much less error prone than having to do an unsafe cast such as 
```ts
supabase.from("users").select("id::text").returns<{ id: string }[]> …
```

Add support for type casting (id::text)

---

src/select-query-parser.ts

Refactor
There is a lot of duplicated code in the query parser, due to the field and renamed field parsing sharing the same code.
The parsing of a field is extracted out to a separate `ParseField` helper, which can be reused to detect both a renamed field and non-renamed fields. I also updated some comments for accuracy.

refactor: query parser cleanup

---

src/select-query-parser.ts
test/index.test-d.ts

Feature.
The `...` spread operator is not supported in select queries.
The `...` spread operator is correctly supported.
This PR is stacked on top of and should be merged after #496.
Closes #459.
Although there are a couple of existing PRs which implement the same feature, I think this is the most accurate (due to the use of the new `ParseField` helper in #496).

feat: parse spread operators in select queries

---

src/select-query-parser.ts
test/index.test-d.ts

Feature.
Empty embedded resources, which were added in PostgREST v11, are not supported by the select query parser.
Support is added for empty embedded resources.
This PR is stacked on top of #497.
Closes https://github.com/supabase/postgrest-js/issues/445.

feat: query parser: handle empty embedded resources `()`

---

src/select-query-parser.ts
test/index.test-d.ts

Feature
The types for select queries do not have types for `count` since it is not a column of the table.
Types for `count` are added to all tables, since it is an aggregate which supported by PostgREST and is widely used in the Supabase-js documentation as well.
This PR is stacked on top of #497.
Closes https://github.com/supabase/postgrest-js/issues/447, https://github.com/supabase/postgrest-js/issues/479.
I'm not sure if the handling of the cardinality is correct for this.

feat: query parser: add types for `count`

---

src/select-query-parser.ts
test/index.test-d.ts

Feature.
[Aggregate functions](https://supabase.com/blog/postgrest-aggregate-functions), added in Postgrest v12, are not supported in the query parser.
Aggregate functions are now supported in the query parser.
Closes #520.
I also split out some of logic into separate helper types and added more docs to make it slightly more comprehensible.

feat: query parser: Add support for aggregate functions

---

src/select-query-parser.ts
test/index.test-d.ts

Makes embedded many-to-one resource type non-null when using inner join
Inner joined resources are nullable, even though in practice they must always exist
Fixes inner joined embedded resource type
fixes #456

Make embedded resource non-nullable if using inner join

---

src/PostgrestClient.ts
test/basic.ts
test/index.test-d.ts

Same changes as https://github.com/supabase/supabase-js/pull/984

feat: typecheck table names in `.from()`

---

src/PostgrestClient.ts
test/basic.ts
test/transforms.ts

feature
No way to use `.rpc()` with GET
The request will be performed with GET when using `.rpc()` with `get: true`.
In read-replica setups, it's common to deny POST/PATCH/etc. on the API gateway level. PostgREST allows performing queries in read-only access mode via stable/immutable functions, but it wouldn't work on this read-replica setup.

feat: `.rpc()` with GET

---

src/PostgrestClient.ts
test/basic.ts
test/db/00-schema.sql
test/types.ts

Bug fix
This isn't an issue on `POST` because upon `JSON.stringify()`, all object fields with a value of `undefined` gets omitted

fix: ignore undefined args when using rpc with head/get

---

src/PostgrestClient.ts
test/basic.ts
test/db/00-schema.sql
test/types.ts

Bug fix
rpc() with HEAD/GET using an array param gives a `malformed array literal` error

fix: rpc w/ HEAD/GET w/ array param

---

src/select-query-parser.ts
test/index.test-d.ts

Select query type parser feature/bugfix
```ts
.select("a_onetoone_rel!inner(*)")
```
results in a nullable `a_onetoone_rel`, while it should be non-nullable due to `!inner`
Detects this case and removes nullability of the inner one-to-one relationship.
non one-to-one case was fixed in #458

detect !inner in one-to-one relationships

---

src/PostgrestTransformBuilder.ts

if you're seeing offset from the first row of the table then I think the end offset would `to + 1` for the defined function.

offset should be `to + 1` not `from + to` in function documentation.

---

package-lock.json
package.json
src/index.ts
test/smoke.cjs
test/smoke.mjs
tsconfig.json
tsconfig.module.json
wrapper.mjs

Relanding https://github.com/supabase/postgrest-js/pull/540/commits/6ac04ffd404265230d4aa2c262970ce976ff8ab1, but fixed to support this usecase:
```js
import * as ns from "@supabase/postgrest-js"
new ns.PostgrestClient()
```

Reland ESM fix

---

src/PostgrestBuilder.ts
test/basic.ts
test/index.test-d.ts

Feature
Currently you cannot use the postgrest-js to add additional headers which however is required in use-cases such as described in https://supabase.com/docs/guides/api/securing-your-api?queryGroups=database-method&database-method=sql&queryGroups=pre-request&pre-request=rate-limit-per-ip 
One can pass `additionalHeaders` and does not have to build a custom wrapper.

Update PostgrestClient.ts to allow for additional headers on-demand

---

test/basic.ts
test/db/01-dummy-data.sql
test/db/docker-compose.yml
test/filters.ts
test/resource-embedding.ts
test/transforms.ts

- Upgrade the postgrest docker image version to match recent one used in supabase
- Add some more data to the tests to assert postgrest runtime behavior on some corner case
- Update all data snapshots in the tests

chore: upgrade postgrest tests image add some more test data

---

src/index.ts

Exporting the custom `PostgrestError` error, not just the type, so we can check `instanceof PostgresError` in code.

Export PostgresError

---

src/PostgrestError.ts
src/types.ts

Fixes
> Type `PostgrestError` is not assignable to type `PostgrestError`.
Type `PostgrestError`and class `PostgrestError` are not compatible
Use class `PostgrestError` instead of type `PostgrestError`, remove type `PostgrestError`
https://github.com/supabase/postgrest-js/issues/561

Use class PostgrestError instead of type PostgrestError, remove type PostgrestError

---

src/select-query-parser/parser.ts
src/select-query-parser/result.ts
src/select-query-parser/utils.ts
test/select-query-parser/parser.test-d.ts
test/select-query-parser/select.test-d.ts

- Fix a bug where !inner contained whitespace before embedding
- Fix a bug where the user facing error would be a nested type [cf](https://github.com/supabase/supabase-js/issues/943#issuecomment-2428602323) unwrap it into a plain string in the final result instead.

fix(types): select query error results and !inner whitespaces

---

src/select-query-parser/result.ts
src/select-query-parser/utils.ts
test/index.test-d.ts
test/select-query-parser/select.test-d.ts

Revert the change made here: https://github.com/supabase/postgrest-js/pull/564
As the unwrapping of the errors introduced an issue with the final result type making the `Json` fields unwrapped as well.
So we'll still have some errors with `SelectQueryError<...>` and the user will sometimes need to access the property in error to get the full error message `result.field.errorField` but that's the lesser evil.
Also removed the `RequiredHint` type as it wasn't flattened in the end result anymore and TS would show it templated like so `RequireHintingSelectQueryError<'table', 'relationsName'>` instead of the plain error message. Use directly `SelectQueryError` instead.
Add any other context or …

fix(parser): revert error unwrapping

---

src/select-query-parser/result.ts
src/select-query-parser/utils.ts
test/select-query-parser/default-inference-d.ts

Fixes the regression in the types inferences if the client is called without a valid schema and defaulted to any
Context: https://discord.com/channels/839993398554656828/1300816893682126912/1301172995326476288

fix(types): types result with schema as any

---

src/select-query-parser/utils.ts
test/select-query-parser/types.test-d.ts
test/types.ts

- Re-introduce deduplication logic for relationships https://github.com/supabase/postgrest-js/pull/558#discussion_r1787643350 for retro-compatibility

fix(types): add deduplication helpers for retro-compatibility

---

src/select-query-parser/result.ts
test/select-query-parser/default-inference-d.ts

- Detected a bug for the "any" schema case while upgrading the workers dependency this make the inference logic more recursive reducing the chances of error and restore the type to match what was generated on `2.46.1`

fix(types): inference for default any schema

---

wrapper.mjs

As per title
`PostgrestError` is not properly exported
`PostgrestError` is properly exported

fix: Add missing PostgrestError export to wrapper.mjs

---

src/index.ts

Hi all! This PR simply re-exports a couple helper types that many of us were using to strongly type our query responses
Please let me know if I can help improve this!
Ever since 1.15.6, these types had been removed, they were internal but recent discussion is that these should be re-exposed
It used to be
```
import { GenericSchema, GenericTable } from "@supabase/postgrest-js/dist/module/types";
import { GetResult } from "@supabase/postgrest-js/dist/module/select-query-parser";
```
See #551 
It is now:
```
import { GetResult, GenericSchema, GenericTable } from "@supabase/postgrest-js";
```
In order to do something like the following:
```
type Collection = SelectPublic<"Collection", "id,imageObjectId,type,name,workspaceId">
```
We can build a helper …

Re-exports GetResult and Generic helpers to type Postgrest Queries

---

src/PostgrestFilterBuilder.ts
test/index.test-d.ts

I believe that when TypeScript resolves overloads, it squashes our 2 variants together, as they are not specific enough to be made distinct. I'm not exactly sure why it doesn't always favor the "more specific" type, but it is what it is.
Second overload can be squashed down into a single one, making overloads unnecessary at all and we can express the type definition directly in the implementation.
(we can also unify most if not all filters using this syntax, but it's your call and I didn't want to make this PR unnecessarily big)
Here's test playground for the issue:
https://www.typescriptlang.org/play/?ssl=15&ssc=1&pln=16&pc=1#code/PTAEFpNAhAlB5A0gUQHIFgBQWAuBPABwFNRYB7Ad1AF5QBvLUUASwBMAuUAZxwCdmAdgHMANI1C8yAGyKcA5AEEAIgFkAkqjmgAPqDkBVAMrJYcrAF8sWAGYBXAQGMczMgJZdyMgIq2ivPAA8AMLStgC2AqgAhmE …

fix: Correctly validate enum values in eq, neq and in methods

---

src/PostgrestBuilder.ts
src/PostgrestTransformBuilder.ts
test/index.test-d.ts

When using throwOnError(), the response type is now more strictly typed:
- Data is guaranteed to be non-null
- Response type is controlled by generic ThrowOnError boolean parameter
Fixes #563

fix(types): type result for throwOnError responses

---

test/basic.ts
test/db/00-schema.sql
test/db/01-dummy-data.sql
test/filters.ts
test/transforms.ts
test/types.ts

Follow-up: https://github.com/supabase/postgrest-js/pull/594
Leverage low hanging fruits tests improving coverage

chore(test): add additional tests improving test coverage

---

src/select-query-parser/parser.ts
src/select-query-parser/result.ts
src/select-query-parser/utils.ts
test/basic.ts
test/index.test-d.ts
test/select-query-parser/parser.test-d.ts
test/select-query-parser/result.test-d.ts
test/select-query-parser/select.test-d.ts
test/types.ts

Allow users to override Json type with custom types, and take into account the "json accessor" to infer the proper resulting type.
Given a table defined like so:
```
type CustomJsonType = {
foo: string
bar: {
baz: number
}
en: 'ONE' | 'TWO' | 'THREE'
}
table: {
data: CustomJsonType | null
}
```
The following behavior is observed:
```ts
select(`data`) -> {data: CustomJsonType | null}
select(`data->bar`) -> {bar: Json}
select(`data->>bar`) -> {bar: string}
select(`data->>en`) -> {bar: string}
select(`data->bar->baz`) -> {baz: Json}
```
```ts
select(`data`) -> {data: CustomJsonType | null}
select(`data->bar`) -> { bar:  { baz: number } }
// Preserve the postgrest casting behaviour due to ->> accessor
select(`data->>bar`) -> {bar: string}
// Preserve the union of string
select(`data->>en`) -> …
```

feat(types): add json path type inference

---

package-lock.json
package.json
src/PostgrestFilterBuilder.ts
test/issue-1354-d.ts
test/relationships.ts

Bug fix a case on typescript > 4.5.5 where using `MergeDeep` override lead to an error of `Type instantiation is excessively deep and possibly infinite`. Use a trick to "force typescript to infer final type" instead of doing a shallow inspection and warning about possible infinite recursion.
This is a bit black magic'ish but it fix the issue on the reproduction case 😅 
Related: https://github.com/supabase/supabase-js/issues/1354

fix(types): type instantiation is excessively deep and possibly infinite

---

src/PostgrestBuilder.ts
src/types.ts
test/basic.ts
test/override-types.test-d.ts

- Add `overrideTypes` method allow both partial and complete override of the return type, do partial override by default
@kamilogorek mentioned that we often had to port a lot of properties definition in order to override a single field when using `.returns` method.
This new method introduce a way to perform "partial override" per default, and allow the user to have similar behavior than the current `.returns` method by providing the option `{ merge: false }`.
This make this kind of type override where we only want to override `func_call` result easier to maintain.
**Before**:
```ts
const results = await getOrThrowTyped(
readWriteNext
.from('sometable')
.select(
'id, projects!projects_sometable_id_fkey(ref, name), func_call(id)'
)
.eq('slug', 'some-slug') …
```

feat(types): add override types method

---

jest.config.js
src/PostgrestBuilder.ts
src/PostgrestTransformBuilder.ts
src/types.ts
test/basic.ts
test/override-types.test-d.ts
test/returns.test-d.ts

- Allow to use returns at the end of the call chain after a .single()
- Add deprecation warning to move toward explicit overrideTypes method
- Add cast checking basic logic, an array should be declared if the result is an array, an object if the result is an object
Goes along: 
https://github.com/supabase/postgrest-js/pull/603

fix(types): returns type casting

---

src/types.ts
test/override-types.test-d.ts

Upgrading `supabase-js` and trying things out in our own repository, I spotted some bugs with the way the merging was done for some cases notably:
1. The properties weren't properly overwrote by the new value if it existed in the original ( that's on me for not writing this basic test 😓)
2. If we wanted to override a "nullable object" such as one within a json field, it wasn't possible to do so without re-writing the whole object, instead of just the property we wanted. This has been changed and now we'll deep-merge and rely on the new casted type to know if we must preserve the optionality or not.
3. Related to 2 but for relations (such as inner) or embeded arrays relationships, it wasn't possible to override the type of one property in the embeded tables. This is now possible by …

fix(types): override types deep merge

---

src/PostgrestBuilder.ts
src/types.ts
test/override-types.test-d.ts
test/types.ts

- When a relation doesn't exist, or that type inference fail to resolve it the new type should be the source of truth for the result. In such case, we don't "merge" the properties together, but just replace the error with the user provided type.
- When chaining the override with `.maybeSingle` preserve the optionality of the result
- Allow merging between literal object and non literal one eg:
```ts
// Given some property like
{
someProperty: Record<string, Json | null>
}
// calling
overrideType<{ someProperty: { literalProperty: string }  }>()
// result in:
{
[key: string]: Json | null
someProperty: { literalProperty: string }
} 
```

fix(types): overrideTypes work on invalid embeded relation

---

src/types.ts
test/override-types.test-d.ts
test/returns.test-d.ts

Slightly changes the output of the error, as when using:
`.overrideTypes<MyType>()`
for an array of results - I was getting error pointing me to use `.returns<Array<YourType>>` which is currently deprecated. 
I've made a message clear for users that gets this error from `.overrideTypes` as well as for `.returns` enjoyers. 
It returns an error message that can be misleading and pointing to use deprecated features.

fix(types): outdated error message

---

jest.config.js
package-lock.json
package.json
src/select-query-parser/result.ts
test/relationships-join-operations.test.ts
test/relationships.test.ts
test/types.override.ts
tsconfig.test.json

Still in the idea to make a more straightforward, unified and strongly typed values for our tests: 
- Introduce `zod` schemas and re-use the same schemas to both:
- infer the expected result type
- Ensure that the runtime result type match the validation of the schema
- Doing so, found a bug where self-referencing embeding via columns name would cause an unwanted intersection and fixed it.

chore(tests): setup zod type checking unify

---

test/max-affected.test.ts
test/relationships-aggregate-operations.test.ts
test/relationships-join-operations.test.ts
test/relationships-spread-operations.test.ts
test/relationships.test.ts
test/resource-embedding.test.ts
test/rpc.test.ts

- Continue work started in: https://github.com/supabase/postgrest-js/pull/627 and leverage zod schema for runtime types shapes validations and type check tests on more tests.

chore(tests): add zod schema validation to more tests

---

.github/workflows/preview-release.yml
README.md

Infrastructure improvement - adds a preview release workflow for easier testing of changes.
Contributors and maintainers need to manually build and test changes locally or wait for official releases to test package changes.
- Adds automated preview release workflow using [`pkg.pr.new`](https://github.com/stackblitz-labs/pkg.pr.new)
- Triggers on pushes to `master` branch and PRs with the `trigger: preview` label
- Automatically publishes preview packages that can be installed and tested
- Provides temporary package URLs for quick testing without affecting the main package
This workflow allows for:
- Quick testing of PR changes before merging
- Easy collaboration on features by sharing preview package links
- Reduced friction in the development and review process
The workflow uses the …

chore: add preview release

---

.github/workflows/preview-release.yml

CI/CD enhancement - Improves the preview release workflow and cross-repository testing integration.
- Preview releases are created but there's no automated way to test compatibility with downstream packages
- No cross-repository testing between `auth-js` and `supabase-js`
- Manual testing required to verify changes don't break integration points
- Limited feedback loop for developers on cross-package compatibility
- **Automated Cross-Repo Testing**: Preview releases automatically trigger compatibility tests in `supabase-js`
- **Smart Triggering**: Only runs on actual source code changes (src/, package files, tsconfig) to avoid unnecessary builds
- **Enhanced Control**: Manual workflow dispatch with configurable options for target branch and test triggering
- **Better UX**: PR comments …

chore: trigger supabase-js tests

---

.github/workflows/preview-release.yml
src/PostgrestClient.ts
src/index.ts
src/types.ts

was causing issues when used together with supabase-js & ssr

fix: inline `GetGenericDatabaseWithOptions`

---

.github/workflows/preview-release.yml

Change event trigger from `pull_request` to `pull_request_target`.
Event for triggering a PR release is `pull_request`. This results in PRs from forks not being able to trigger the cross-repo testing.
Event trigger is now `pull_request_target`. Using `pull_request_target` allows access to secrets when PRs come from forks. This is secure, since only us, maintainers, can add the label to trigger the PR release.

chore: fix preview release to use correct target
