- docker-compose.yml
- src/index.js
PostgREST had this fixed in v7.0.1: https://postgrest.org/en/v7.0.0/releases/v7.0.1.html
> fix: multischema RPC Content-Profile header

- src/builder.ts
Docs update
Current JSDoc doesn't include complete types and other things. (https://github.com/supabase/postgrest-js/issues/111)
JSDoc is pretty much improved overall.
Its my first PR to an open source project, let me know if there's anything wrong!
> JSDoc Improvements

- src/lib/types.ts
fixes https://github.com/supabase/postgrest-js/issues/158
> Convert PostgrestError to a type

- package-lock.json
- package.json
- src/lib/PostgrestTransformBuilder.ts
- src/lib/types.ts
- test/__snapshots__/index.test.ts.snap
- test/transforms.ts
> Create maybeSingle() function

- src/lib/PostgrestFilterBuilder.ts
Bug fix.
https://github.com/supabase/supabase-js/issues/203
See title.
> fix: change match's value type to unknown

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/lib/PostgrestTransformBuilder.ts
- src/lib/types.ts
- test/basic.ts
- test/transforms.ts
- tsconfig.json
> feat: AbortSignal

- package-lock.json
- package.json
NPM package audit – fix CVEs
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ node-fetch is vulnerable to Exposure of Sensitive            │
│               │ Information to an Unauthorized Actor                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cross-fetch                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cross-fetch > node-fetch                                     │ …
```
> Bump cross-fetch to resolve CVE-2022-0235 (and typedoc)

- README.md
> update(README.md): replace `.io` to `.com`

- src/PostgrestBuilder.ts
- src/PostgrestFilterBuilder.ts
- src/PostgrestQueryBuilder.ts
- src/types.ts
- test/__snapshots__/index.test.ts.snap
- test/basic.ts
- test/filters.ts
- test/transforms.ts
Please review https://github.com/supabase/postgrest-js/pull/274 first 🙏
BREAKING CHANGE: obselete the following previously-deprecated features:
- filter shorthands (e.g. `cs` vs. `contains`)
- `body` in response (vs. `data`)
- `upsert`ing thru `.insert()`
> feat: obsolete deprecated stuff

- src/PostgrestTransformBuilder.ts
https://github.com/supabase/postgrest-js/pull/277#issuecomment-1157728112
> feat: omit `.nullsfirst`/`.nullslast` by default

- src/PostgrestBuilder.ts
- src/PostgrestTransformBuilder.ts
- test/transforms.ts
Will then delete the `next` branch
> Merge next to rc

- package.json
Context: https://supabase.slack.com/archives/C038D5ENAAH/p1660811517460669
> fix: missing src in package

- src/PostgrestClient.ts
- src/PostgrestFilterBuilder.ts
- src/PostgrestQueryBuilder.ts
- src/PostgrestTransformBuilder.ts
- src/select-query-parser.ts
- src/types.ts
- test/basic.ts
- test/db/00-schema.sql
- test/types.ts
Context: https://github.com/supabase/cli/issues/385
Pending on https://github.com/supabase/cli/pull/432
> feat(types): support views

- package-lock.json
- package.json
- src/PostgrestClient.ts
- src/PostgrestFilterBuilder.ts
- src/PostgrestQueryBuilder.ts
- src/PostgrestTransformBuilder.ts
- test/basic.ts
- test/transforms.ts
Also update test suite - previously it was saying green even though the test was failing: https://github.com/supabase/postgrest-js/runs/8200926135?check_suite_focus=true#step:4:49
No logic change.
Updated typedocs can be seen [here](https://supabase.github.io/postgrest-js/).
> docs: update typedoc

- .gitignore
- v2/spec.json
Adds spec.json, generated using the older tsdoc 0.22.16
(also adds a .gitignore to make committing easier)
> Add regenerated spec file with tsdoc 0.22.16

- package-lock.json
- package.json
https://github.com/supabase/postgrest-js/actions/runs/3419512607
> chore(deps): fix conflict

- src/PostgrestBuilder.ts
- test/basic.ts
Fixes https://github.com/supabase/postgrest-js/issues/295
> fix: wrong response on update w/o match

- src/PostgrestBuilder.ts
- test/transforms.ts
Closes https://github.com/supabase/postgrest-js/issues/418
> fix: populate `details` on FetchError

- package-lock.json
- package.json
- src/PostgrestBuilder.ts
Part of fixing https://github.com/supabase/supabase-js/issues/612
> fix: use @supabase/node-fetch

- package-lock.json
- package.json
- src/PostgrestBuilder.ts
fixes https://github.com/supabase/postgrest-js/issues/465
> fix: revert using @supabase/node-fetch

- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
- tsconfig.module.json
- wrapper.mjs
Support CommonJS & ESM. Previously the ESM build (dist/module) is broken - it's recognized as CommonJS.
For more on dual-packaging: https://nodejs.org/api/packages.html#dual-commonjses-module-packages
> fix: use proper dual-packaging

- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
- tsconfig.module.json
- wrapper.mjs
This reverts commit 2c4e846c8f697f760e15e06a60014e8b93bf3b34.
Fixes https://github.com/supabase/postgrest-js/issues/538
> Revert "fix: use proper dual-packaging"

- package.json
Fixes https://github.com/supabase/postgrest-js/issues/545
> fix: esm typings

- src/PostgrestFilterBuilder.ts
Follow up to https://github.com/supabase/postgrest-js/pull/588 and https://github.com/supabase/postgrest-js/pull/589
> fix: also validate enums in views

- .github/workflows/ci.yml
- package.json
Bug fix, feature, docs update, ...
> chore: add test coverage to postgrest-js

- package.json
- test/db/docker-compose.yml
- test/scripts/update-json-type.js
- test/types.generated.ts
- Regenerate database types
- Fix data types override generation
> chore(deps): bump postgres-meta to 0.91.5
